---
- name: check for existing install...
  stat:
    path: '{{ keycloak_install_dir }}'
  changed_when: False
  register: keycloak_binary
- when: not keycloak_binary.stat.exists
  block:
    - name: download tgz
      get_url:
        url: '{{ keycloak_tgz_url }}'
        dest: /tmp/{{ keycloak_tgz }}
        checksum: '{{ keycloak_checksum }}'
        mode: 0644
    - name: unarchive
      unarchive:
        remote_src: yes
        src: /tmp/{{ keycloak_tgz }}
        dest: '{{ keycloak_parent_install_dir }}'
        creates: '{{ keycloak_install_dir }}'
  always:
    - name: cleanup...
      file:
        path: /tmp/{{ keycloak_tgz }}
        state: absent

- name: link
  file:
    src: '{{ keycloak_install_dir }}'
    dest: '{{ keycloak_link_dir }}'
    state: link

- name: add to path
  with_items:
    - f: keycloak.sh
      d: /etc/profile.d
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m|default("0644") }}'

- name: Create wildfly group
  group:
    name: '{{ wildfly_group }}'
    state: present

- name: Create wildfly user
  user:
    name: '{{ wildfly_user }}'
    group: '{{ wildfly_group }}'
    home: '{{ keycloak_parent_install_dir }}/keycloak-{{ keycloak_ver }}'
    create_home: false
    shell: '/sbin/nologin'
    state: present
    
- name: Change ownership of keycloak directories
  file:
    path: '{{ keycloak_parent_install_dir }}/keycloak-{{ keycloak_ver }}'
    recurse: true
    owner: '{{ wildfly_user }}'
    group: '{{ wildfly_group }}'

- name: Create wildfly config directory
  file:
    path: '{{ wildfly_conf_dir }}'
    state: directory

#- name: Copy wildfly config to config directory
#  copy:
#    remote_src: true
#    src: '{{ keycloak_parent_install_dir }}/keycloak-{{ keycloak_ver }}/docs/contrib/scripts/systemd/wildfly.conf'
#    dest: '{{ wildfly_conf_dir }}/wildfly.conf'
#    owner: root
#    group: root
#    mode: 0644

- name: Copy wildfly config to config directory
  template:
    src: 'templates/wildfly.conf.j2'
    dest: '{{ wildfly_conf_dir }}/wildfly.conf'
    owner: root
    group: root
    mode: 0644

#- name: Copy wildfly systemd service file
#  copy:
#    remote_src: true
#    src: '{{ keycloak_parent_install_dir }}/keycloak-{{ keycloak_ver }}/docs/contrib/scripts/systemd/wildfly.service'
#    dest: '/etc/systemd/system/wildfly.service'
#    owner: root
#    group: root
#    mode: 0644

- name: Copy wildfly systemd service file
  template:
    src: 'templates/wildfly.service.j2'
    dest: '/usr/lib/systemd/system/wildfly.service'
    owner: root
    group: root
    mode: 0644

- name: Copy wildfly launcher
  copy:
    remote_src: true
    src: '{{ keycloak_parent_install_dir }}/keycloak-{{ keycloak_ver }}/docs/contrib/scripts/systemd/launch.sh'
    dest: '{{ keycloak_parent_install_dir }}/keycloak-{{ keycloak_ver }}/bin/launch.sh'
    owner: root
    group: root
    mode: 0755

- name: Start wildfly service
  systemd:
    name: wildfly
    state: started
    enabled: true
    masked: false
    daemon_reload: true
